/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TailorMaker;
import javax.swing.JFrame;

public class App {
    
    public static void main(String[] args) {
        System.out.print( System.getProperty("sun.java.command"));
  System.out.println(System.getenv("JAVA_MAIN_CLASS"));
          show_pallete();
    }
                  
   public static void show_pallete(){
       
       JFrame frame;
       frame = new ColorPallete();

       frame.setLocationRelativeTo(null);
       frame.pack();

       frame.setVisible(true);
       
   }
}
