/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TailorMaker;

import javax.swing.ImageIcon;
import javax.swing.*;  
import javax.swing.JButton;
import java.awt.event.*;  

import javax.swing.JFrame;

import java.io.* ;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.FileReader;

import java.awt.Rectangle;


import javax.imageio.ImageIO;

public class Jumper extends javax.swing.JFrame {
    public static boolean open_on_open = false;
    public static int c;
    public static int a;
    public static int x;
    public static int y;
    public static int tot_x;
    public static int tot_y;
    public static int x2;
    public static int y2;
    public static int tot_x2;
    public static int tot_y2;
    public static int total;
    public static int total2;
    public static int current;
    public static int current2;
    public static String s = "/swhite.png";
    public static int u;
    public static int v;
    public static int colour1;
    public static int colour2;
    public static String path_to_colour1 = "/swhite.png";
    public static String path_to_colour2 = "/swhite.png";
    public static int pattern;
    public static int plus_x;
    public static int plus_y;
    public static int plus_x2;
    public static int plus_y2;
    public static boolean disable_half;
    public static boolean disable_pixel;
    public static DefaultListModel listModel;
    public static DefaultListModel listModel2;
    public static String item_adder_string = "";
    public static String current_colour_pixel= "White";
    public static String current_colour_pixel2= "White"; 
    public static String clicked;
    public static String string_append;
    public static boolean is_correct_component = false;
    public static String current_line;
    public static int current_line_number;
    public static FileInputStream filestream;
    public static InputStreamReader br;
    public static int i=0;
    public static String Open_Colour = "";
    public static int result;
    public static BufferedImage img = null;
    public static Rectangle componentRect = null;
    public static String lineIWant_process4;   
    public static String lineIWant_process1;
    public Jumper() {
        initComponents();
        tot_x = 64;
        tot_y = 64;
        tot_x2 =64;
        tot_y2=64;
        listModel = new DefaultListModel();
        listModel2 = new DefaultListModel();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knitting Pattern Window");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void exportTexture() {                                             
        
        BufferedImage screenshotImage = new BufferedImage(
        this.getBounds().width, this.getBounds().height,BufferedImage.TYPE_INT_RGB);
        this.paint(screenshotImage.getGraphics());
         JFrame parentFrame = new JFrame();
 
                       current2=0;
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setDialogTitle("Open A Knit...");
                    int file_name2 = fileChooser.showOpenDialog(parentFrame);
                    if (file_name2 == JFileChooser.APPROVE_OPTION) {
                    //add the items to list
                    File exportedPath = fileChooser.getSelectedFile();
        try {
            ImageIO.write(screenshotImage, "png", new File(exportedPath.getAbsolutePath()));
        } catch (IOException ex) {
            System.err.println("ImageIsuues");
        }
                    }  
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        componentRect = this.getBounds();
         current2=0;
         current=0;
        if (open_on_open==true){
           pattern=2;
                    total2=tot_x2*tot_y2;
                    JFrame parentFrame = new JFrame();
 
                      
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setDialogTitle("Open A Knit...");
                    int file_name2 = fileChooser.showOpenDialog(parentFrame);
                    if (file_name2 == JFileChooser.APPROVE_OPTION) {
                    //add the items to list
                    File fileToOpen = fileChooser.getSelectedFile();
                  try
                        (
                           FileReader       input = new FileReader(fileToOpen.getAbsolutePath());
                           LineNumberReader count = new LineNumberReader(input);
                        )
                        {
                           while (count.skip(Long.MAX_VALUE) > 0)
                           {
                              // Loop just in case the file is > Long.MAX_VALUE or skip() decides to not read the entire file
                           }

                            result = count.getLineNumber()+1;                                    // +1 because line index starts at 0
                        } catch (IOException e) {}
                            System.out.print("Wools Total:"+result);
                    
                    try {
                        FileInputStream filestream= new FileInputStream(fileToOpen.getAbsolutePath());
                        BufferedReader br2 = new BufferedReader(new InputStreamReader(filestream));
                     
                        
                        String line = br2.readLine();
			while (current2 < result) {
				System.out.println(line);
				// read next line
				line = br2.readLine();
			
                           
                           
                          lineIWant_process4 =line.replaceAll("\\d","");
                           
                           
                        
                           
                           
                                if ("wool:b:Red:".equals(lineIWant_process4)){
                                   Open_Colour ="/shue+360.png";
                                   
                                }
                                if ("wool:b:Raddish:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+330.png";
                                   
                                     
                                }
                                if ("wool:b:Purple:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+300.png";
                                    
                                   
                                }
                                if ("wool:b:Dark Purple:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+270.png";
                                    
                                }
                                if ("wool:b:Dark Blue:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+240.png";
                                     
                                }
                                if ("wool:b:Blue:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+210.png";
                                     
                                }
                                if ("wool:b:Cyan:".equals(lineIWant_process4)){
                                    Open_Colour="/shue+180.png";
                                     
                                }
                                if ("wool:b:Mint:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+150.png";
                                     
                                }
                                if ("wool:b:Green:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+120.png";
                                   
                                }
                                if ("wool:b:Grass:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+90.png";
                                     
                                }
                                if ("wool:b:Yellow:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+60.png";
                                     
                                }
                                if ("wool:b:Orange:".equals(lineIWant_process4)){
                                    Open_Colour ="/shue+30.png";
                                     
                                }
                                if ("wool:b:White:".equals(lineIWant_process4)){
                                    Open_Colour ="/swhite.png";
                                    
                                  
                                }
                                if ("wool:b:Black:".equals(lineIWant_process4)){
                                    Open_Colour="/sblack.png";
                                    
                                }
                       JButton b=new JButton(new ImageIcon(Jumper.class.getResource(Open_Colour))); 
                    b.setDisabledIcon(new ImageIcon(Jumper.class.getResource(Open_Colour)));
                    b.setDoubleBuffered(true);
                    
                    b.setSize(18,18);  
                    listModel.addElement(lineIWant_process1);
                   
                   
                    if (x > tot_x){
                        x = 0;
                        y = y+1;
                    }
                   current2=current2+1;
                   x+=1;
                    
                      
                   

                    
                    
                    
                    //move the knitting needle
                    
                    b.setLocation(x*16, y*16);
                    b.setVisible(true);
                    b.setFocusable(false);
                    b.addActionListener(new ActionListener(){  
                    public void actionPerformed(ActionEvent e){  
                        
                        
                      
                        
                     
 

                     
                                is_correct_component =true;
                                
                            
                                
                                
                                
                          if ((c == 1) & (is_correct_component)){
                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Red"+ ":";
                                        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+360.png")));
                                            }
                                              
                                        }
                                        
                                       

                        }
                        if ((c == 2) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Raddish"+ ":";
                                            for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+330.png")));
                                            }
                                              
                                            }   
                        }                               
                        if ((c == 3) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Purple"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+300.png")));
                                            }
                                              
                                            }   

                        }
                        if ((c == 4) & (is_correct_component)){

                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Dark Purple"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+270.png")));
                                            }
                                              
                                            }   

                        }                        
                        if ((c == 5) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Dark Blue"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+340.png")));
                                            }
                                              
                                            }   

                        }                      
                        if ((c == 6) & (is_correct_component)){





                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Blue"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+210.png")));
                                            }
                                              
                                            }   

                        }                        
                        if ((c == 7) & (is_correct_component)){



                                       string_append = "wool:" + (b.getName().substring(0)) + ":" + "Cyan"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+180.png")));
                                            }
                                              
                                            }   

                        }                       
                        if ((c == 8) & (is_correct_component)){




                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Mint"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+150.png")));
                                            }
                                              
                                            }   
                        }                        
                        if ((c == 9) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Green"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+120.png")));
                                            }
                                              
                                            }   

                        }                       
                        if ((c == 10) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Grass"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+90.png")));
                                            }
                                              
                                            }   

                        }                       
                        if ((c == 11) & (is_correct_component)){


                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Yellow"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+90.png")));
                                            }
                                              
                                            }   
                        }                       
                        if ((c == 12) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Orange"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+30.png")));
                                            }
                                              
                                            }   

                        }                        
                        if ((c == 13) & (is_correct_component)){





                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Black"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/sblack.png")));
                                            }
                                              
                                            }   

                        }
                        if ((c == 14) & (is_correct_component)){




                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "White"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/swhite.png")));
                                            }
                                              
                                            }   

                        }
                            
                    }         
                                         
        });
            add(b);
            b.setContentAreaFilled(false);
            b.setBorderPainted(false);
            b.setName(current+"b");
            
       
                              
       
                    
                    
                    
                    
                    
                            
                        }
                    }catch (IOException e ){}}
                               
                 
                 
        
        
                    
                    
                    
                    
                    
                   current_line_number = 0;
                  plus_x=0;
                  plus_y=0;
                  plus_x2=0;
                  plus_y2=0;  
                  c=0;
                  a=0;
                  x=0;
                  y=0;
                  u=0;
                  v=0;
                  tot_x=0;
                  tot_y=0;
                  x2=0;
                  y2=0;
                  tot_x2=0;
                  tot_y2=0;
                  total=0;
                  total2=0;
                  current=0;
                  current2=0;    
                    
                    
                    
                    
                    
        
       }
                      
    
      if (open_on_open==false){
       
      
     
        
        
        a = 1;
        pattern = 2;

        // the screen height
      
        if (colour1 == 1){
            path_to_colour1 ="/shue+360.png";
            current_colour_pixel = "Red";
        }
        if (colour1 == 2){
            path_to_colour1 ="/shue+330.png";
             current_colour_pixel = "Raddish";
        }
        if (colour1 == 3){
            path_to_colour1 ="/shue+300.png";
             current_colour_pixel = "Purple";
        }
        if (colour1 == 4){
            path_to_colour1 ="/shue+270.png";
             current_colour_pixel = "Dark Purple";
        }
        if (colour1 == 5){
            path_to_colour1 ="/shue+240.png";
             current_colour_pixel = "Dark Blue";
        }
        if (colour1 == 6){
            path_to_colour1 ="/shue+210.png";
             current_colour_pixel = "Blue";
        }
        if (colour1 == 7){
            path_to_colour1 ="/shue+180.png";
             current_colour_pixel = "Cyan";
        }
        if (colour1 == 8){
            path_to_colour1 ="/shue+150.png";
             current_colour_pixel = "Mint";
        }
        if (colour1 == 9){
            path_to_colour1 ="/shue+120.png";
             current_colour_pixel = "Green";
        }
        if (colour1 == 10){
            path_to_colour1 ="/shue+90.png";
             current_colour_pixel = "Grass";
        }
        if (colour1 == 11){
            path_to_colour1 ="/shue+60.png";
             current_colour_pixel = "Yellow";
        }
        if (colour1 == 12){
            path_to_colour1 ="/shue+30.png";
             current_colour_pixel = "Orange";
        }
        if (colour1 == 13){
            path_to_colour1 ="/swhite.png";
             current_colour_pixel = "White";
        }
        if (colour1 == 14){
            path_to_colour1 ="/sblack.png";
             current_colour_pixel = "Black";
        }
        if (colour2 == 1){
            path_to_colour2 ="/shue+360.png";
            current_colour_pixel2 = "Red";
        }
        if (colour2 == 2){
            path_to_colour2 ="/shue+330.png";
            current_colour_pixel2 = "Raddish";
        }
        if (colour2 == 3){
            path_to_colour2 ="/shue+300.png";
            current_colour_pixel2 = "Purple";
        }
        if (colour2 == 4){
            path_to_colour2 ="/shue+270.png";
            current_colour_pixel2 = "Dark Purple";
        }
        if (colour2 == 5){
            path_to_colour2 ="/shue+240.png";
            current_colour_pixel2 = "Dark Blue";
        }
        if (colour2 == 6){
            path_to_colour2 ="/shue+210.png";
            current_colour_pixel2 = "Blue";
        }
        if (colour2 == 7){
            path_to_colour2 ="/shue+180.png";
            current_colour_pixel2 = "Cyan";
        }
        if (colour2 == 8){
            path_to_colour2 ="/shue+150.png";
            current_colour_pixel2 = "Mint";
        }
        if (colour2 == 9){
            path_to_colour2 ="/shue+120.png";
            current_colour_pixel2 = "Green";
        }
        if (colour2 == 10){
            path_to_colour2 ="/shue+90.png";
            current_colour_pixel2 = "Grass";
        }
        if (colour2 == 11){
            path_to_colour2 ="/shue+60.png";
            current_colour_pixel2 = "Yellow";
        }
        if (colour2 == 12){
            path_to_colour2 ="/shue+30.png";
            current_colour_pixel2 = "Orange";
        }
        if (colour2 == 13){
            path_to_colour2 ="/swhite.png";
            current_colour_pixel2 = "White";
        }
        if (colour2 == 14){
            path_to_colour2 ="sblack.png";
            current_colour_pixel2 = "Black";
        }
            
        
        
        
        
        //pattern1
        if (a == 1){
            setLayout(null);
            System.out.println("Going with Default Patch");
            x = 0;

            y = 0;

            total =tot_x * tot_y;
            
            // this should be set to the form before
            //demo default pattern, red and black

            while (current<total){
                total=tot_x*tot_y;
                    if (x > tot_x){
                        x = 0;
                        y = y+1;
                    }
                   current=current+1;
                   if ( current % 2 == 0 ){
                         s = path_to_colour1;
                         item_adder_string = "wool:" + String.valueOf(current) + "b:" + current_colour_pixel + ":";
                   }else{
                         s = path_to_colour2; 
                         item_adder_string = "wool:" + String.valueOf(current) + "b:" + current_colour_pixel2 + ":";
                   }
                    x  += 1;
           
                    
                    JButton b=new JButton(new ImageIcon(Jumper.class.getResource(s))); 
                    b.setDisabledIcon(new ImageIcon(Jumper.class.getResource(s)));
                    b.setDoubleBuffered(true);
                    
                    b.setSize(18,18);  
                    b.setLocation(x*16, y*16);
                    b.setVisible(true);
                    b.setFocusable(false);
                    if ((current % 2 == 0) & (disable_half == true)){
                        b.setEnabled(false);
                    }
                    if ((current % 2 != 0) & (disable_half == true)){
                        b.setEnabled(true);
                    }
                     if ((current % 2 == 0) & (disable_half == false)){
                        b.setEnabled(true);
                    }
                    if ((current % 2 != 0) & (disable_half == false)){
                        b.setEnabled(true);
                    }               
                    
                    
                    
                    listModel.addElement(item_adder_string);
                    System.out.println(item_adder_string);
                    // saveing method ideas
                    
                    
                    // remove 
                    //listModel.add("new item replaced")// add again


                    
                    //listModel.clear()   // new clear (all)
                    

                    b.addActionListener(new ActionListener(){  
                    public void actionPerformed(ActionEvent e){  
                        
                        
                      
                        
                     
 

                     
                                is_correct_component =true;
                                
                            
                                
                                
                                
                        if ((c == 1) & (is_correct_component)){
                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Red"+ ":";
                                        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+360.png")));
                                            }
                                              
                                        }
                                        
                                       

                        }
                        if ((c == 2) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Raddish"+ ":";
                                            for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+330.png")));
                                            }
                                              
                                            }   
                        }                               
                        if ((c == 3) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Purple"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+300.png")));
                                            }
                                              
                                            }   

                        }
                        if ((c == 4) & (is_correct_component)){

                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Dark Purple"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+270.png")));
                                            }
                                              
                                            }   

                        }                        
                        if ((c == 5) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Dark Blue"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+340.png")));
                                            }
                                              
                                            }   

                        }                      
                        if ((c == 6) & (is_correct_component)){





                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Blue"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+210.png")));
                                            }
                                              
                                            }   

                        }                        
                        if ((c == 7) & (is_correct_component)){



                                       string_append = "wool:" + (b.getName().substring(0)) + ":" + "Cyan"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+180.png")));
                                            }
                                              
                                            }   

                        }                       
                        if ((c == 8) & (is_correct_component)){




                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Mint"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+150.png")));
                                            }
                                              
                                            }   
                        }                        
                        if ((c == 9) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Green"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+120.png")));
                                            }
                                              
                                            }   

                        }                       
                        if ((c == 10) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Grass"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+90.png")));
                                            }
                                              
                                            }   

                        }                       
                        if ((c == 11) & (is_correct_component)){


                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Yellow"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+90.png")));
                                            }
                                              
                                            }   
                        }                       
                        if ((c == 12) & (is_correct_component)){



                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Orange"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/shue+30.png")));
                                            }
                                              
                                            }   

                        }                        
                        if ((c == 13) & (is_correct_component)){





                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "Black"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.print("Changed Pixel");
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/sblack.png")));
                                            }
                                              
                                            }   

                        }
                        if ((c == 14) & (is_correct_component)){




                                        string_append = "wool:" + (b.getName().substring(0)) + ":" + "White"+ ":";
        for(int integer1=0; i < listModel.getSize(); integer1++){
                                            if (!listModel.getElementAt(integer1).toString().contains("wool:"+b.getName())) {
                                               
                                            } else {
                                                listModel.set(integer1,string_append);
                                                System.out.println(string_append);
                                                b.setIcon(new ImageIcon(Jumper.class.getResource("/swhite.png")));
                                            }
                                              
                                            }   


                            }
                            
                    }           
                      
        });
            add(b);
            b.setContentAreaFilled(false);
            b.setBorderPainted(false);
            b.setName(current+"b");

           
            
    }                                        
        
            
            
            
        
    }//GEN-LAST:event_formWindowOpened
       }
                  current_line_number = 0;
                  plus_x=0;
                  plus_y=0;
                  plus_x2=0;
                  plus_y2=0;  
                  c=0;
                  a=0;
                  x=0;
                  y=0;
                  u=0;
                  v=0;
                  tot_x=0;
                  tot_y=0;
                  x2=0;
                  y2=0;
                  tot_x2=0;
                  tot_y2=0;
                  total=0;
                  total2=0;
                  current=0;
                  current2=0;
       } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jumper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jumper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jumper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jumper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jumper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
